"""CRUD operations aggregator."""

# This is an aggregator module by design - it re-exports all CRUD operations
# WPS203: 80 imported names > 50 (aggregator purpose)
# WPS235: multiple imports from submodules > 8 (aggregator purpose)
# WPS410: __all__ is standard Python for public API
# WPS412: __init__.py with imports is standard for packages

from bot.database.crud._companies import (
    CompanyCreateParams,
    create_company,
    delete_company,
    get_all_companies,
    get_company_by_id,
    update_company,
)
from bot.database.crud._documents import (
    DocumentCreateParams,
    create_document,
    delete_document,
    get_document_by_id,
    get_documents_by_project_id,
    get_documents_by_task_id,
    update_document,
)
from bot.database.crud._feedback import (
    FeedbackCreateParams,
    create_feedback,
    delete_feedback,
    get_feedback_by_id,
    get_feedbacks_by_project_id,
)
from bot.database.crud._meetings import (
    GISLogCreateParams,
    MeetingCreateParams,
    add_meeting_participant,
    create_gis_check_log,
    create_meeting,
    delete_gis_log,
    delete_meeting,
    get_gis_logs_by_meeting_id,
    get_meeting_by_id,
    get_meetings_by_project_id,
    update_meeting_status,
    update_participant_status,
)
from bot.database.crud._notifications import (
    NotificationCreateParams,
    create_notification,
    delete_notification,
    get_notification_by_id,
    get_notifications_by_user_id,
    mark_all_notifications_as_read,
    mark_notification_as_read,
)
from bot.database.crud._params import (
    ProjectCreateParams,
    StageCreateParams,
    TaskCreateParams,
    UserCreateParams,
    UserUpdateParams,
)
from bot.database.crud._projects import (
    assign_manager_to_project,
    assign_task_to_performer,
    create_project,
    create_stage,
    create_task,
    delete_project,
    delete_stage,
    delete_task,
    get_all_projects,
    get_all_tasks,
    get_pending_projects,
    get_project_by_id,
    get_projects_by_client_id,
    get_projects_by_manager_id,
    get_stage_by_id,
    get_stages_by_project_id,
    get_task_by_id,
    get_tasks_by_performer_id,
    get_tasks_by_project_id,
    update_project_status,
    update_stage_status,
    update_task_status,
)
from bot.database.crud._statistics import (
    get_manager_projects_count,
    get_performer_tasks_count,
    get_projects_count_by_status,
    get_tasks_count_by_status,
    get_total_projects_count,
    get_total_tasks_count,
    get_total_users_count,
    get_users_count_by_role,
)
from bot.database.crud._users import (
    create_user,
    delete_user,
    get_all_users,
    get_user_by_id,
    get_user_by_telegram_id,
    get_users_by_role,
    update_user_profile,
    update_user_role,
)

__all__ = [
    "CompanyCreateParams",
    "DocumentCreateParams",
    "FeedbackCreateParams",
    "GISLogCreateParams",
    "MeetingCreateParams",
    "NotificationCreateParams",
    "ProjectCreateParams",
    "StageCreateParams",
    "TaskCreateParams",
    "UserCreateParams",
    "UserUpdateParams",
    "add_meeting_participant",
    "assign_manager_to_project",
    "assign_task_to_performer",
    "create_company",
    "create_document",
    "create_feedback",
    "create_gis_check_log",
    "create_meeting",
    "create_notification",
    "create_project",
    "create_stage",
    "create_task",
    "create_user",
    "delete_company",
    "delete_document",
    "delete_feedback",
    "delete_gis_log",
    "delete_meeting",
    "delete_notification",
    "delete_project",
    "delete_stage",
    "delete_task",
    "delete_user",
    "get_all_companies",
    "get_all_projects",
    "get_all_tasks",
    "get_all_users",
    "get_company_by_id",
    "get_document_by_id",
    "get_documents_by_project_id",
    "get_documents_by_task_id",
    "get_feedback_by_id",
    "get_feedbacks_by_project_id",
    "get_gis_logs_by_meeting_id",
    "get_manager_projects_count",
    "get_meeting_by_id",
    "get_meetings_by_project_id",
    "get_notification_by_id",
    "get_notifications_by_user_id",
    "get_pending_projects",
    "get_performer_tasks_count",
    "get_project_by_id",
    "get_projects_by_client_id",
    "get_projects_by_manager_id",
    "get_projects_count_by_status",
    "get_stage_by_id",
    "get_stages_by_project_id",
    "get_task_by_id",
    "get_tasks_by_performer_id",
    "get_tasks_by_project_id",
    "get_tasks_count_by_status",
    "get_total_projects_count",
    "get_total_tasks_count",
    "get_total_users_count",
    "get_user_by_id",
    "get_user_by_telegram_id",
    "get_users_by_role",
    "get_users_count_by_role",
    "mark_all_notifications_as_read",
    "mark_notification_as_read",
    "update_company",
    "update_document",
    "update_meeting_status",
    "update_participant_status",
    "update_project_status",
    "update_stage_status",
    "update_task_status",
    "update_user_profile",
    "update_user_role",
]
